function Hd = Filter_1
%FILTER_1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 26-Oct-2022 09:15:42

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 28.8;  % Sampling Frequency

Fpass = 1.4;               % Passband Frequency
Fstop = 2;                 % Stopband Frequency
Dpass = 0.028774368332;    % Passband Ripple
Dstop = 0.00031622776602;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
